name: products_telegram_bot_ai_android
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/products_telegram_bot_ai
repository: https://github.com/azkadev/products_telegram_bot_ai
issue_tracker: https://github.com/azkadev/products_telegram_bot_ai/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - products_telegram_bot_ai
#   - products_telegram_bot_ai_flutter
#   - products_telegram_bot_ai_dart

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 